[["exception-handling.html", "Chapter 6 Exception Handling 6.1 Catching Error 6.2 Custom Exception", " Chapter 6 Exception Handling The try statement works as follows: First, the try clause (the statement(s) between the try and except keywords) is executed If no exception occurs, the except clause is skipped and execution of the try statement is finished If an exception occurs during execution of the try clause, the rest of the clause is skipped. Then if its type matches the exception named after the except keyword, the except clause is executed, and then execution continues after the try statement If an exception occurs which does not match the exception named in the except clause, it is passed on to outer try statements; if no handler is found, it is an unhandled exception and execution stops with a message as shown above A try statement may have more than one except clause, to specify handlers for different exceptions. Try-Except-Finally try: # code that may cause exceptions except: # code that handle exceptions finally: # code that clean up # this block optional 6.1 Catching Error Different exception object has different attributes. try: a = 1 + &#39;a&#39; ## catch specific error except TypeError as err: print(&#39;I know this error !!!!&#39;, &#39;\\n Error: &#39;, err, &#39;\\n Args: &#39;, err.args, &#39;\\n Type: &#39;, type(err)) ## Catch all other error except Exception as err: print( &#39;Error: &#39;, err, &#39;\\nArgs: &#39;, err.args, &#39;\\nType: &#39;, type(err)) ## I know this error !!!! ## Error: unsupported operand type(s) for +: &#39;int&#39; and &#39;str&#39; ## Args: (&quot;unsupported operand type(s) for +: &#39;int&#39; and &#39;str&#39;&quot;,) ## Type: &lt;class &#39;TypeError&#39;&gt; 6.2 Custom Exception try: raise Exception(&#39;bloody&#39;, &#39;hell&#39;) #simulate exception except Exception as err: print( &#39;Error: &#39;, err, &#39;\\nArgs: &#39;, err.args, &#39;\\nType: &#39;, type(err)) ## Error: (&#39;bloody&#39;, &#39;hell&#39;) ## Args: (&#39;bloody&#39;, &#39;hell&#39;) ## Type: &lt;class &#39;Exception&#39;&gt; "],["404.html", "Page not found", " Page not found The page you requested cannot be found (perhaps it was moved or renamed). You may want to try searching to find the page's new location, or use the table of contents to find the page you are looking for. "]]
